# Generated by Django 5.0.3 on 2024-06-01 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profiel',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profiel_pic',
            new_name='profile_pic',
        ),
    ]
